apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: worker-controller
build:
  artifacts:
#    - image: controller
#      docker:
#        dockerfile: Dockerfile
    - image: worker-controller/sample-worker
      docker:
        dockerfile: sample-worker.dockerfile
manifests:
  kustomize:
    paths:
      - internal/samples
#      - config/crd
profiles:
#  - name: default
#    manifests:
#      kustomize:
#        paths:
#          - config/default
#  - name: manager
#    manifests:
#      kustomize:
#        paths:
#          - config/manager
#  - name: prometheus
#    manifests:
#      kustomize:
#        paths:
#          - config/prometheus
#  - name: rbac
#    manifests:
#      kustomize:
#        paths:
#          - config/rbac
  - name: samples
    manifests:
      kustomize:
        paths:
          - internal/samples
