---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - update
- apiGroups:
  - temporal.io
  resources:
  - temporalconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalworkers/finalizers
  verbs:
  - update
- apiGroups:
  - temporal.io
  resources:
  - temporalworkers/status
  verbs:
  - get
  - patch
  - update
