# permissions for end users to edit temporalconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: temporalconnection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: temporal-worker-controller
    app.kubernetes.io/part-of: temporal-worker-controller
    app.kubernetes.io/managed-by: kustomize
  name: temporalconnection-editor-role
rules:
- apiGroups:
  - temporal.io.temporal.io
  resources:
  - temporalconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io.temporal.io
  resources:
  - temporalconnections/status
  verbs:
  - get
