# permissions for end users to view workerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workerdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worker-controller
    app.kubernetes.io/part-of: worker-controller
    app.kubernetes.io/managed-by: kustomize
  name: workerdeployment-viewer-role
rules:
- apiGroups:
  - temporal.io.temporal.io
  resources:
  - workerdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.io.temporal.io
  resources:
  - workerdeployments/status
  verbs:
  - get
