# permissions for end users to view temporalworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: temporalworker-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worker-controller
    app.kubernetes.io/part-of: worker-controller
    app.kubernetes.io/managed-by: kustomize
  name: temporalworker-viewer-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalworkers/status
  verbs:
  - get
