apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: samples
build:
  artifacts:
    - image: worker-controller/sample-worker
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - .
