apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: samples
build:
  artifacts:
    - image: worker
      context: worker
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DD_GIT_COMMIT_SHA: "{{ .IMAGE_TAG }}"
          DD_GIT_REPOSITORY_URL: "github.com/DataDog/temporal-worker-controller"
  tagPolicy:
    gitCommit:
      variant: CommitSha
deploy:
  kubeContext: minikube
  kubectl: {}
manifests:
  rawYaml:
    - temporal_worker.yaml
resourceSelector:
  allow:
    - groupKind: "TemporalWorker.temporal.io"
      image: [".*"]
      labels: [".*"]
