apiVersion: temporal.io/v1alpha1
kind: TemporalWorker
metadata:
  labels:
    app.kubernetes.io/name: hello-world-worker
    app.kubernetes.io/instance: sample
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-worker
      app.kubernetes.io/instance: sample
  template:
    spec:
      containers:
        - name: main
          image: worker
          imagePullPolicy: Never
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
  workerOptions:
    connection: dev-server
    temporalNamespace: "default"
    taskQueue: "hello_world"
  rolloutStrategy:
#    manual: {}
#    blueGreen: {}
    progressive:
      steps:
       - rampPercentage: 10
         pauseDuration: 30s
       - rampPercentage: 50
         pauseDuration: 30s
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: dev-server
spec:
  hostPort: "host.minikube.internal:7233"
