// Unless explicitly stated otherwise all files in this repository are licensed under the MIT License.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2024 Datadog, Inc.

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibleVersionSet) DeepCopyInto(out *CompatibleVersionSet) {
	*out = *in
	if in.InactiveBuildIDs != nil {
		in, out := &in.InactiveBuildIDs, &out.InactiveBuildIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibleVersionSet.
func (in *CompatibleVersionSet) DeepCopy() *CompatibleVersionSet {
	if in == nil {
		return nil
	}
	out := new(CompatibleVersionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextVersionSet) DeepCopyInto(out *NextVersionSet) {
	*out = *in
	if in.VersionSet != nil {
		in, out := &in.VersionSet, &out.VersionSet
		*out = new(CompatibleVersionSet)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextVersionSet.
func (in *NextVersionSet) DeepCopy() *NextVersionSet {
	if in == nil {
		return nil
	}
	out := new(NextVersionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorker) DeepCopyInto(out *TemporalWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorker.
func (in *TemporalWorker) DeepCopy() *TemporalWorker {
	if in == nil {
		return nil
	}
	out := new(TemporalWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerList) DeepCopyInto(out *TemporalWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TemporalWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerList.
func (in *TemporalWorkerList) DeepCopy() *TemporalWorkerList {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerSpec) DeepCopyInto(out *TemporalWorkerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	out.WorkerOptions = in.WorkerOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerSpec.
func (in *TemporalWorkerSpec) DeepCopy() *TemporalWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerStatus) DeepCopyInto(out *TemporalWorkerStatus) {
	*out = *in
	if in.NextVersionSet != nil {
		in, out := &in.NextVersionSet, &out.NextVersionSet
		*out = new(NextVersionSet)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultVersionSet != nil {
		in, out := &in.DefaultVersionSet, &out.DefaultVersionSet
		*out = new(CompatibleVersionSet)
		(*in).DeepCopyInto(*out)
	}
	if in.DeprecatedVersionSets != nil {
		in, out := &in.DeprecatedVersionSets, &out.DeprecatedVersionSets
		*out = make([]*CompatibleVersionSet, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CompatibleVersionSet)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerStatus.
func (in *TemporalWorkerStatus) DeepCopy() *TemporalWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOptions) DeepCopyInto(out *WorkerOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOptions.
func (in *WorkerOptions) DeepCopy() *WorkerOptions {
	if in == nil {
		return nil
	}
	out := new(WorkerOptions)
	in.DeepCopyInto(out)
	return out
}
