//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibleVersionSet) DeepCopyInto(out *CompatibleVersionSet) {
	*out = *in
	if in.InactiveBuildIDs != nil {
		in, out := &in.InactiveBuildIDs, &out.InactiveBuildIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibleVersionSet.
func (in *CompatibleVersionSet) DeepCopy() *CompatibleVersionSet {
	if in == nil {
		return nil
	}
	out := new(CompatibleVersionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerDeployment) DeepCopyInto(out *WorkerDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerDeployment.
func (in *WorkerDeployment) DeepCopy() *WorkerDeployment {
	if in == nil {
		return nil
	}
	out := new(WorkerDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerDeploymentList) DeepCopyInto(out *WorkerDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkerDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerDeploymentList.
func (in *WorkerDeploymentList) DeepCopy() *WorkerDeploymentList {
	if in == nil {
		return nil
	}
	out := new(WorkerDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerDeploymentSpec) DeepCopyInto(out *WorkerDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
	out.WorkerOptions = in.WorkerOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerDeploymentSpec.
func (in *WorkerDeploymentSpec) DeepCopy() *WorkerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerDeploymentStatus) DeepCopyInto(out *WorkerDeploymentStatus) {
	*out = *in
	in.DefaultVersionSet.DeepCopyInto(&out.DefaultVersionSet)
	if in.DeprecatedVersionSets != nil {
		in, out := &in.DeprecatedVersionSets, &out.DeprecatedVersionSets
		*out = make([]CompatibleVersionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerDeploymentStatus.
func (in *WorkerDeploymentStatus) DeepCopy() *WorkerDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOptions) DeepCopyInto(out *WorkerOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOptions.
func (in *WorkerOptions) DeepCopy() *WorkerOptions {
	if in == nil {
		return nil
	}
	out := new(WorkerOptions)
	in.DeepCopyInto(out)
	return out
}
