apiVersion: temporal.io/v1alpha1
kind: TemporalWorker
metadata:
  name: sample
  labels:
    app.kubernetes.io/name: hello-world-worker
    app.kubernetes.io/instance: sample
spec:
  # Configuration for connecting to Temporal service
  workerOptions:
    connection: dev-server
    temporalNamespace: "default"
    taskQueue: "hello_world"
  # How to cut over new workflow executions to the latest worker version
  rolloutStrategy:
    allAtOnce: {}
  # Desired number of worker replicas
  replicas: 1
  # Desired specification for worker pods
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:9090/metrics",
                  "metrics": [".*"]
                }
              ]
            }
          }
    spec:
      containers:
        - name: main
          image: worker
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: dev-server
spec:
  hostPort: "host.minikube.internal:7233"
